# Generated by Django 6.0.5 on 2026-05-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameTimeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_day', models.IntegerField(default=1)),
                ('game_year', models.IntegerField(default=2026)),
                ('game_month', models.IntegerField(default=1)),
                ('season', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Game Time State',
                'verbose_name_plural': 'Game Time State',
            },
        ),
    ]
