# Generated by Django 6.0.5 on 2026-05-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_time', '0002_game_hour_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametimestate',
            name='max_game_days',
            field=models.IntegerField(default=0, help_text='全服最大可推进天数，0表示无限制'),
        ),
    ]
