# Generated by Django 6.0.5 on 2026-06-09 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_4_normal_phase', models.IntegerField(default=15, help_text='优秀：概率不变的次数')),
                ('quality_4_guarantee_at', models.IntegerField(default=20, help_text='优秀：必出次数')),
                ('quality_4_ramp_probabilities', models.JSONField(default=list, help_text='优秀：概率提升阶段的概率数组（百分比），如 [10,25,50,80,100]')),
                ('quality_4_time_range', models.IntegerField(default=15, help_text='优秀保底触发时，烹饪时间区间（±N秒）')),
                ('quality_5_normal_phase', models.IntegerField(default=50, help_text='极品：概率不变的次数')),
                ('quality_5_guarantee_at', models.IntegerField(default=60, help_text='极品：必出次数')),
                ('quality_5_ramp_probabilities', models.JSONField(default=list, help_text='极品：概率提升阶段的概率数组（百分比）')),
                ('quality_5_time_range', models.IntegerField(default=5, help_text='极品保底触发时，烹饪时间区间（±N秒）')),
                ('quality_6_normal_phase', models.IntegerField(default=75, help_text='绝品：概率不变的次数')),
                ('quality_6_guarantee_at', models.IntegerField(default=90, help_text='绝品：必出次数')),
                ('quality_6_ramp_probabilities', models.JSONField(default=list, help_text='绝品：概率提升阶段的概率数组（百分比）')),
                ('quality_6_time_range', models.IntegerField(default=0, help_text='绝品保底触发时，烹饪时间区间（±N秒，0=精确）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '保底配置',
                'verbose_name_plural': '保底配置',
            },
        ),
        migrations.CreateModel(
            name='PityCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_4', models.IntegerField(default=0, help_text='连续未出优秀的次数')),
                ('count_5', models.IntegerField(default=0, help_text='连续未出极品的次数')),
                ('count_6', models.IntegerField(default=0, help_text='连续未出绝品的次数')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pity_counter', to='account.gameaccount', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '保底计数器',
                'verbose_name_plural': '保底计数器',
            },
        ),
    ]
