# Generated by Django 6.0.5 on 2026-05-15 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100, unique=True)),
                ('action_points', models.IntegerField(default=100)),
                ('action_points_max', models.IntegerField(default=1000)),
                ('game_day', models.IntegerField(default=1)),
                ('game_year', models.IntegerField(default=2026)),
                ('game_month', models.IntegerField(default=1)),
                ('season', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['player_id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_id', models.CharField(max_length=100)),
                ('title_name', models.CharField(max_length=100)),
                ('obtained_at', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='player.playerstate')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('ingredients', models.JSONField(default=list)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='player.playerstate')),
            ],
            options={
                'unique_together': {('player', 'recipe_name')},
            },
        ),
    ]
