# Generated by Django 6.0.5 on 2026-05-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_game_hour_minute'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100, unique=True)),
                ('ingredients', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['recipe_name'],
            },
        ),
    ]
