# Generated by Django 6.0.5 on 2026-05-20 07:39

import django.db.models.deletion
from django.db import migrations, models


def backfill_default_recipe(apps, schema_editor):
    """按 recipe_name 匹配 DefaultRecipe，填充 PlayerRecipe.default_recipe FK。"""
    PlayerRecipe = apps.get_model("player", "PlayerRecipe")
    DefaultRecipe = apps.get_model("player", "DefaultRecipe")

    defaults = {d.recipe_name: d for d in DefaultRecipe.objects.all()}
    updated = 0
    for pr in PlayerRecipe.objects.all():
        default = defaults.get(pr.recipe_name)
        if default:
            pr.default_recipe = default
            pr.save(update_fields=["default_recipe"])
            updated += 1

    print(f"\n  [数据迁移] 回填完成: {updated}/{PlayerRecipe.objects.count()} 条 PlayerRecipe 已关联 DefaultRecipe")


def reverse_backfill(apps, schema_editor):
    """反向迁移：清空 default_recipe FK。"""
    PlayerRecipe = apps.get_model("player", "PlayerRecipe")
    PlayerRecipe.objects.update(default_recipe=None)


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_defaultrecipe'),
    ]

    operations = [
        # 第一步：加 FK（nullable，允许先加后填）
        migrations.AddField(
            model_name='playerrecipe',
            name='default_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_recipes', to='player.defaultrecipe'),
        ),
        # 第二步：回填数据
        migrations.RunPython(backfill_default_recipe, reverse_backfill),
        # 第三步：删 ingredients
        migrations.RemoveField(
            model_name='playerrecipe',
            name='ingredients',
        ),
    ]
