# Generated by Django 6.0.5 on 2026-05-20 07:48

import django.db.models.deletion
from django.db import migrations, models


def backfill_catalog_recipe(apps, schema_editor):
    """按 recipe_name 匹配完整菜谱目录，填充 PlayerRecipe.catalog_recipe FK。"""
    PlayerRecipe = apps.get_model("player", "PlayerRecipe")
    CatalogRecipe = apps.get_model("recipes", "Recipe")

    catalog_map = {r.recipe_name: r for r in CatalogRecipe.objects.all()}
    updated = 0
    for pr in PlayerRecipe.objects.all():
        catalog = catalog_map.get(pr.recipe_name)
        if catalog:
            pr.catalog_recipe = catalog
            pr.save(update_fields=["catalog_recipe"])
            updated += 1

    print(f"\n  [数据迁移] 回填完成: {updated}/{PlayerRecipe.objects.count()} 条 PlayerRecipe 已关联完整菜谱目录")


def reverse_backfill(apps, schema_editor):
    PlayerRecipe = apps.get_model("player", "PlayerRecipe")
    PlayerRecipe.objects.update(catalog_recipe=None)


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_player_recipe_fk'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        # 第一步：加 catalog_recipe FK
        migrations.AddField(
            model_name='playerrecipe',
            name='catalog_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_recipes', to='recipes.recipe'),
        ),
        # 第二步：回填数据
        migrations.RunPython(backfill_catalog_recipe, reverse_backfill),
        # 第三步：删旧字段
        migrations.RemoveField(
            model_name='playerrecipe',
            name='default_recipe',
        ),
        migrations.RemoveField(
            model_name='defaultrecipe',
            name='ingredients',
        ),
    ]
