# Generated by Django 6.0.5 on 2026-05-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('player', '0006_catalog_recipe_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerResetProxy',
            fields=[
            ],
            options={
                'verbose_name': '玩家重置',
                'verbose_name_plural': '玩家重置',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.gameaccount',),
        ),
        migrations.AddField(
            model_name='playerrecipe',
            name='show_ingredient_count',
            field=models.BooleanField(default=False, help_text='是否在菜谱界面显示食材数量'),
        ),
    ]
