# Generated by Django 6.0.5 on 2026-06-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_playerstate_current_season_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstate',
            name='day_start_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstate',
            name='day_start_money_game_day',
            field=models.IntegerField(default=0, help_text='快照对应的 total_game_days'),
        ),
    ]
