# Generated by Django 6.0.5 on 2026-05-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_type', models.CharField(choices=[('wealth', '富豪榜'), ('output', '产量榜'), ('freshness', '极鲜榜')], max_length=20)),
                ('season_id', models.CharField(max_length=50)),
                ('character_id', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('is_ai', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('avatar_id', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['board_type', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='PendingReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100)),
                ('reward_id', models.CharField(max_length=100, unique=True)),
                ('board_type', models.CharField(max_length=20)),
                ('settlement_type', models.CharField(max_length=20)),
                ('rank', models.IntegerField(default=0)),
                ('rewards', models.JSONField(default=list)),
                ('expire_time', models.BigIntegerField(default=0)),
                ('claimed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-expire_time'],
            },
        ),
        migrations.CreateModel(
            name='ReportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RewardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_type', models.CharField(choices=[('wealth', '富豪榜'), ('output', '产量榜'), ('freshness', '极鲜榜')], max_length=20)),
                ('settlement_type', models.CharField(choices=[('daily', '每日结算'), ('weekly', '每周结算')], max_length=20)),
                ('rank_min', models.IntegerField(default=1)),
                ('rank_max', models.IntegerField(default=1)),
                ('reward_type', models.CharField(max_length=20)),
                ('reward_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['board_type', 'settlement_type', 'rank_min'],
            },
        ),
    ]
