# Generated by Django 6.0.5 on 2026-05-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='dish_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
