# Generated by Django 6.0.5 on 2026-05-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_leaderboardentry_dish_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboardentry',
            options={'ordering': ['board_type', 'game_day', 'rank']},
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='game_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportevent',
            name='game_day',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
