# Generated by Django 6.0.5 on 2026-06-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_alter_leaderboardentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.CharField(max_length=50, unique=True)),
                ('sequence', models.IntegerField(help_text='自增序号', unique=True)),
                ('duration_days', models.IntegerField(default=7, help_text='赛季时长（现实天数）')),
                ('start_time', models.BigIntegerField(help_text='赛季开始时间（epoch seconds）')),
                ('end_time', models.BigIntegerField(help_text='赛季结束时间（epoch seconds）')),
                ('settled', models.BooleanField(default=False, help_text='是否已结算')),
                ('status', models.CharField(choices=[('active', '进行中'), ('ended', '已结束'), ('settled', '已结算')], default='active', max_length=20)),
            ],
            options={
                'verbose_name': '赛季',
                'verbose_name_plural': '赛季',
                'ordering': ['-sequence'],
            },
        ),
        migrations.CreateModel(
            name='SeasonConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_duration_days', models.IntegerField(default=7, help_text='默认赛季天数')),
                ('auto_rotate', models.BooleanField(default=True, help_text='是否自动轮转')),
            ],
            options={
                'verbose_name': '赛季配置',
                'verbose_name_plural': '赛季配置',
            },
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='board_type',
            field=models.CharField(choices=[('wealth', '富豪榜'), ('output', '产量榜'), ('freshness', '极鲜榜'), ('total_wealth', '总富豪榜'), ('total_output', '总产量榜'), ('total_freshness', '总极鲜榜')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rewardconfig',
            name='board_type',
            field=models.CharField(choices=[('wealth', '富豪榜'), ('output', '产量榜'), ('freshness', '极鲜榜'), ('total_wealth', '总富豪榜'), ('total_output', '总产量榜'), ('total_freshness', '总极鲜榜')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rewardconfig',
            name='settlement_type',
            field=models.CharField(choices=[('daily', '每日结算'), ('weekly', '每周结算'), ('season', '赛季结算')], max_length=20),
        ),
    ]
