# Generated by Django 6.0.5 on 2026-06-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_season_seasonconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonconfig',
            name='freshness_top_n',
            field=models.IntegerField(default=3, help_text='极鲜榜每玩家最多上榜菜品数'),
        ),
    ]
