# Generated by Django 6.0.5 on 2026-05-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('Seed', '种子'), ('Commodity', '商品'), ('Furniture', '家具'), ('HoeTool', '锄头'), ('ChopTool', '斧头'), ('BreakTool', '锤子'), ('ReapTool', '镰刀'), ('WaterTool', '水壶'), ('CollectTool', '采集工具'), ('ReapableScenery', '可收割场景'), ('食物', '食物'), ('食材', '食材'), ('肉类', '肉类'), ('蔬菜', '蔬菜'), ('水果', '水果'), ('调料类', '调料类')], default='Commodity', max_length=20)),
                ('item_description', models.TextField(blank=True, default='')),
                ('item_use_radius', models.IntegerField(default=0)),
                ('can_picked_up', models.BooleanField(default=False)),
                ('can_dropped', models.BooleanField(default=False)),
                ('can_carried', models.BooleanField(default=False)),
                ('item_price', models.IntegerField(default=0)),
                ('sell_percentage', models.FloatField(default=0.5)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='items/icons/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['item_id'],
            },
        ),
    ]
