# Generated by Django 6.0.5 on 2026-05-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='collect_max_amount',
            field=models.IntegerField(default=2, help_text='采集时最多获得数量'),
        ),
        migrations.AddField(
            model_name='item',
            name='collect_min_amount',
            field=models.IntegerField(default=1, help_text='采集时最少获得数量'),
        ),
        migrations.AddField(
            model_name='item',
            name='collect_weight',
            field=models.IntegerField(default=100, help_text='采集权重，越大越容易被抽到'),
        ),
    ]
