# Generated by Django 6.0.5 on 2026-05-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_collect_max_amount_item_collect_min_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='collectable',
            field=models.BooleanField(default=True, help_text='是否可被采集'),
        ),
    ]
