# Generated by Django 6.0.5 on 2026-05-15 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.CharField(max_length=100)),
                ('money', models.IntegerField(default=0)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.gameaccount')),
            ],
            options={
                'unique_together': {('player', 'character_id')},
            },
        ),
        migrations.CreateModel(
            name='InventorySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.IntegerField()),
                ('instance_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('item_id', models.IntegerField(default=0)),
                ('item_amount', models.IntegerField(default=0)),
                ('rated', models.BooleanField(default=False)),
                ('rating_price', models.IntegerField(default=-1)),
                ('ingredient', models.CharField(blank=True, default='', max_length=100)),
                ('item_bag_name', models.CharField(blank=True, default='', max_length=100)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='inventory.inventorybag')),
            ],
            options={
                'ordering': ['slot_index'],
                'unique_together': {('bag', 'slot_index')},
            },
        ),
    ]
