# Generated by Django 6.0.5 on 2026-05-16 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.CharField(help_text='对应角色ID，如 player、tjplb', max_length=100, unique=True)),
                ('money', models.IntegerField(default=0, help_text='初始金币')),
            ],
        ),
        migrations.CreateModel(
            name='BagTemplateSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.IntegerField()),
                ('item_id', models.IntegerField(default=0)),
                ('item_amount', models.IntegerField(default=0)),
                ('rated', models.BooleanField(default=False)),
                ('rating_price', models.IntegerField(default=-1)),
                ('ingredient', models.CharField(blank=True, default='', max_length=100)),
                ('item_bag_name', models.CharField(blank=True, default='', max_length=100)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='inventory.bagtemplate')),
            ],
            options={
                'ordering': ['slot_index'],
                'unique_together': {('template', 'slot_index')},
            },
        ),
    ]
