# Generated by Django 6.0.5 on 2026-05-16 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_bagtemplate_bagtemplateslot'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagtemplateslot',
            name='item_bag_name',
        ),
        migrations.RemoveField(
            model_name='bagtemplateslot',
            name='item_id',
        ),
        migrations.AddField(
            model_name='bagtemplateslot',
            name='item',
            field=models.ForeignKey(blank=True, help_text='选择物品', null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AlterField(
            model_name='bagtemplateslot',
            name='item_amount',
            field=models.IntegerField(default=1),
        ),
    ]
