# Generated by Django 6.0.5 on 2026-05-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_bagtemplateslot_item_bag_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBagProxy',
            fields=[
            ],
            options={
                'verbose_name': '背包管理',
                'verbose_name_plural': '背包管理',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventorybag',),
        ),
        migrations.AlterField(
            model_name='bagtemplateslot',
            name='slot_index',
            field=models.IntegerField(default=-1),
        ),
    ]
