# Generated by Django 6.0.5 on 2026-05-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorybagproxy_alter_bagtemplateslot_slot_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagtemplateslot',
            name='cook_time',
            field=models.IntegerField(default=0, help_text='烹饪时长（秒）'),
        ),
        migrations.AddField(
            model_name='bagtemplateslot',
            name='dish_quality',
            field=models.IntegerField(default=3, help_text='品质：1略逊 2一般 3正常 4优秀 5极品 6绝品'),
        ),
        migrations.AddField(
            model_name='inventoryslot',
            name='cook_time',
            field=models.IntegerField(default=0, help_text='烹饪时长（秒）'),
        ),
        migrations.AddField(
            model_name='inventoryslot',
            name='dish_quality',
            field=models.IntegerField(default=3, help_text='品质：1略逊 2一般 3正常 4优秀 5极品 6绝品'),
        ),
        migrations.AlterField(
            model_name='bagtemplateslot',
            name='ingredient',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='inventoryslot',
            name='ingredient',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
