# Generated by Django 6.0.5 on 2026-05-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_bagtemplateslot_cook_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagtemplateslot',
            name='overall_score',
            field=models.IntegerField(default=0, help_text='评价分数 0-100'),
        ),
        migrations.AddField(
            model_name='inventoryslot',
            name='overall_score',
            field=models.IntegerField(default=0, help_text='评价分数 0-100'),
        ),
    ]
