# Generated by Django 6.0.5 on 2026-06-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_bagtemplateslot_overall_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagtemplateslot',
            name='hide_in_shop',
            field=models.BooleanField(default=False, help_text='是否在商店面板中隐藏此物品'),
        ),
        migrations.AddField(
            model_name='inventoryslot',
            name='hide_in_shop',
            field=models.BooleanField(default=False, help_text='是否在商店面板中隐藏此物品'),
        ),
    ]
