# Generated by Django 6.0.5 on 2026-05-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(blank=True, default='', help_text='菜系：川菜、粤菜、浙菜、鲁菜', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='default_cook_time',
            field=models.IntegerField(default=0, help_text='默认烹饪时长（秒）'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='default_dish_quality',
            field=models.IntegerField(default=3, help_text='默认品质：1略逊 2一般 3正常 4优秀 5极品 6绝品'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(default=2, help_text='难度：1简单 2中等 3困难'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dish_category',
            field=models.CharField(blank=True, default='', help_text='分类：主菜/汤品/凉菜/点心/主食', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='serving_style',
            field=models.CharField(blank=True, default='', help_text='上菜形式：大盘/小碟/拼盘/位上', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='taste_profile',
            field=models.CharField(blank=True, default='', help_text='口味标签：甜/咸/辣/酸/鲜', max_length=50),
        ),
    ]
