# Generated by Django 6.0.5 on 2026-05-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_cuisine_recipe_default_cook_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='item_id',
            field=models.IntegerField(),
        ),
    ]
